from building import *

cwd = GetCurrentDir()
src = [
    '../core/transport/shm/segment.cc',
    '../core/transport/shm/shm_conf.cc',
    '../core/transport/shm/state.cc',
    '../core/transport/shm/k230_shm.cc',
    '../core/node/node.cc',
    '../core/pangofly.cc',
    '../examples/core/shm_example.cc',
]

CPPPATH = [
    cwd,
    '..',
]

CPPDEFINES = [
    'RT_USING_NEWLIB',
    'HAVE_CCONFIG_H',
    'PANGOFLY_PLATFORM_K230',
]

group = DefineGroup('pangofly', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
group = group + LinkBridge()

Return('group')