namespace pangofly.examples {

struct ImageFrame {
    int64_t timestamp;
    int32_t width;
    int32_t height;
    int32_t format;
    int32_t stride;
    vector<uint8> data;
};

struct FaceBox {
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    float score;
    int32_t id;
};

struct FaceLandmark {
    int32_t x;
    int32_t y;
};

struct FaceResult {
    int32_t frame_id;
    int64_t timestamp;
    int32_t face_count;
    vector<FaceBox> faces;
    vector<FaceLandmark> landmarks;
    float processing_time_ms;
};

}
