// Face Detection IDL
// Follows OMG IDL 4.2 / DDS-XTypes standard syntax

module FaceDetection {

    // Face bounding box
    struct FaceBox {
        long x;
        long y;
        long width;
        long height;
        float score;
        long id;
    };

    // Face landmark point
    struct FaceLandmark {
        long x;
        long y;
    };

    // Image frame data
    struct ImageFrame {
        long long timestamp;
        long width;
        long height;
        long format;
        long stride;
        sequence<octet> data;
    };

    // Face detection result
    struct FaceResult {
        long frame_id;
        long long timestamp;
        long face_count;
        float processing_time_ms;
        sequence<FaceBox> faces;
        sequence<FaceLandmark> landmarks;
    };

}
