namespace FaceDetection {

struct FaceBox {
    int32 x;
    int32 y;
    int32 width;
    int32 height;
    float32 score;
    int32 id;
};

struct FaceLandmark {
    int32 x;
    int32 y;
};

struct ImageFrame {
    int64 timestamp;
    int32 width;
    int32 height;
    int32 format;
    int32 stride;
    vector<uint8> data;
};

struct FaceResult {
    int32 frame_id;
    int64 timestamp;
    int32 face_count;
    float32 processing_time_ms;
    vector<FaceBox> faces;
    vector<FaceLandmark> landmarks;
};

}
