#include "code_generator.h"
#include "../container/vector.h"
#include "../container/string.h"
#include <algorithm>

namespace pangofly {
namespace idl {

CodeGenerator::CodeGenerator(const std::shared_ptr<IDLDocument>& document)
    : document_(document) {}

std::string CodeGenerator::generate() {
    std::ostringstream oss;
    
    oss << generate_header();
    oss << "\n";
    oss << "#pragma once\n";
    oss << "\n";
    oss << generate_includes();
    oss << "\n";
    oss << "// Begin auto-generated code\n";
    oss << "\n";
    
    for (const auto& ns : document_->namespaces) {
        if (ns.name.empty()) {
            for (const auto& s : ns.structs) {
                oss << generate_struct(*s);
                oss << "\n";
            }
        } else {
            oss << generate_namespace_open(ns.name) << "\n";
            for (const auto& s : ns.structs) {
                oss << "  " << generate_struct(*s);
            }
            oss << "\n" << generate_namespace_close(ns.name) << "\n";
        }
    }
    
    oss << "// End auto-generated code\n";
    
    return oss.str();
}

std::string CodeGenerator::generate_header() {
    return "/*\n"
           " * Pangofly IDL Generated Header\n"
           " * DO NOT EDIT THIS FILE MANUALLY\n"
           " * Auto-generated by Pangofly IDL Compiler (IDC)\n"
           " */\n";
}

std::string CodeGenerator::generate_includes() {
    return "#include \"pangofly/idl/container/vector.h\"\n"
           "#include \"pangofly/idl/container/string.h\"\n"
           "#include <cstdint>\n"
           "#include <cstring>\n"
           "#include <algorithm>\n"
           "#include <stdexcept>\n";
}

std::string CodeGenerator::generate_namespace_open(const std::string& ns) {
    return "namespace " + ns + " {\n";
}

std::string CodeGenerator::generate_namespace_close(const std::string& ns) {
    (void)ns; // suppress unused warning
    return "} // namespace\n";
}

std::string CodeGenerator::generate_struct(const Struct& s) {
    std::ostringstream oss;
    std::string class_name = s.name;
    
    if (class_name.find("::") != std::string::npos) {
        class_name = class_name.substr(class_name.find("::") + 2);
    }
    
    oss << "class " << class_name << " {\n";
    oss << "public:\n";
    
    for (const auto& field : s.fields) {
        oss << "  " << generate_field(field) << "\n";
    }
    
    oss << "\n";
    oss << "private:\n";
    for (const auto& field : s.fields) {
        std::string cpp_type = generate_type_name(*field.type);
        if (field.type->is_vector() || field.type->is_string()) {
            cpp_type += "::Data";
        }
        oss << "  " << cpp_type << " " << field.name << "_;\n";
    }
    
    oss << "};\n";
    
    return oss.str();
}

std::string CodeGenerator::generate_field(const Field& f) {
    std::ostringstream oss;
    std::string cpp_type = generate_type_name(*f.type);
    oss << cpp_type << " " << f.name << "() { return " << cpp_type << "{" << f.name << "_}; }";
    return oss.str();
}

std::string CodeGenerator::generate_getter(const Field& f) {
    std::ostringstream oss;
    std::string cpp_type = generate_type_name(*f.type);
    oss << cpp_type << " " << f.name << "() { return " << f.name << "_; }";
    return oss.str();
}

std::string CodeGenerator::generate_type_name(const Type& t) {
    switch (t.kind) {
        case TypeKind::PRIMITIVE_BOOL:    return "bool";
        case TypeKind::PRIMITIVE_INT8:    return "int8_t";
        case TypeKind::PRIMITIVE_UINT8:   return "uint8_t";
        case TypeKind::PRIMITIVE_INT16:   return "int16_t";
        case TypeKind::PRIMITIVE_UINT16:  return "uint16_t";
        case TypeKind::PRIMITIVE_INT32:   return "int32_t";
        case TypeKind::PRIMITIVE_UINT32:  return "uint32_t";
        case TypeKind::PRIMITIVE_INT64:   return "int64_t";
        case TypeKind::PRIMITIVE_UINT64:  return "uint64_t";
        case TypeKind::PRIMITIVE_FLOAT32: return "float";
        case TypeKind::PRIMITIVE_FLOAT64: return "double";
        case TypeKind::USER_DEF:          return t.name;
        case TypeKind::STRING:            return "pangofly::String";
        case TypeKind::VECTOR: {
            auto vec_type = std::dynamic_pointer_cast<VectorType>(
                std::make_shared<Type>(t));
            if (vec_type && vec_type->element_type) {
                return "pangofly::Vector<" + 
                       generate_type_name(*vec_type->element_type) + ">";
            }
            return "pangofly::Vector<void>";
        }
        case TypeKind::FIXED_ARRAY: {
            auto arr_type = std::dynamic_pointer_cast<FixedArrayType>(
                std::make_shared<Type>(t));
            if (arr_type) {
                return "std::array<" + arr_type->name + ", " + 
                       std::to_string(arr_type->size) + ">";
            }
            return "std::array<void, 0>";
        }
        default:
            return "void";
    }
}

} // namespace idl
} // namespace pangofly
